#!/bin/bash

echo "installing k10"

#https://docs.kasten.io/install/install.html#prerequisites
kubectl get namespace kasten-io || kubectl create namespace kasten-io
helm repo add kasten https://charts.kasten.io/

# install k10
helm status k10 --namespace kasten-io || helm install k10 kasten/k10 --namespace=kasten-io

# Digital Ocean compatibility
# TODO check for annotation rather than overwrite
kubectl annotate volumesnapshotclass do-block-storage k10.kasten.io/is-snapshot-class=true --overwrite

# install mysql
echo "installing mysql..."
kubectl get namespace zac-stewart || kubectl create namespace zac-stewart
helm repo add stable https://kubernetes-charts.storage.googleapis.com/
helm status mysql --namespace zac-stewart || helm install mysql stable/mysql --namespace=zac-stewart

echo "applying backup policy..."
kubectl apply -f /mysql-backup-policy.yaml