apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: zac-stewart-backup
  namespace: kasten-io
spec:
  comment: ""
  frequency: "@daily"
  actions:
    - action: backup
  retention:
    daily: 7
    weekly: 4
    monthly: 12
    yearly: 7
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - zac-stewart
