#!/bin/bash

echo "resetting cluster..."
echo "uninstalling k10 helm chart"
helm uninstall k10 --namespace kasten-io

echo "deleting kasten-io namespace"
kubectl delete namespace kasten-io

echo "deleting zac-stewart namespace"
kubectl delete namespace zac-stewart